### ISSUE TITLE
Showing Raw Images of Leap device in WebGL/browser

### ISSUE THREAD

**Issue by GMelencio** [Abantech/Efficio#61]
We have client that wants to see the raw camera data from the Leap Device via Javascript. So basically they wanbt to see the same ting that the Leap Visualizer shows you (the Leap's raw camera data) with the human bones detected being superimposed.

This is possible to do with C#/unity but wondered if the javascript fans ion our team are up for the challenge of showing that it can be done.

@theo-armour ?

**Comment by theo-armour** [comment]
https://developer.leapmotion.com/documentation/javascript/devguide/Leap_Images.html

I may have at if the data is available USB or whatever - but not today
