### ISSUE TITLE
Positional Data Input

### ISSUE THREAD

**Issue by james-h-stephens** [Abantech/Efficio#9]
Create abstract positional classes for determining location, elevation, and heading.

**Comment by joeabsoftdev** [comment]
Would you like this portion to be generic, device-specific, or to be and/or include a device selector coupled to a specific-to-generic positional data input-to-middleware converter?

**Comment by james-h-stephens** [comment]
We should create a middleware device-agnostic interface for representing this kind of data. Then, we can create wrappers around specific devices to have them conform to these interfaces.

For example, the Altimeter sensor abstract class has a virtual method that retrieves the altitude from a given sensor.  The SampleAltimeter class is an concrete class that extends the Altimeter class. When queried, the SampleAltimeter class will always return a value of "3 meters".

You can see that the Drone asset that was also included as a sample is an asset containing multiple sensors, including the SampleAltimeter. Let me know of those clear it up.

**Comment by joeabsoftdev** [comment]
That answers the high-level structure for me. Can we engineer a converter to automatically handle device-type recognition and pathway modulation (and hopefully a little bit of optimization) between a group of wrappers on both sides of the central middleware?

**Comment by james-h-stephens** [comment]
@joeabsoftdev I'll be honest, I didn't understand anything you just said haha

**Comment by james-h-stephens** [comment]
There seems to be several different positional data types. I will mark this more vague request as closed and will create new feature requests for the different positional data types
